services:
  postgres:
    image: postgres:15
    container_name: orders_postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "55432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"